-- ==============================================
--  Base de datos para el Sistema Integral de Gestión Contable y Facturación ISP
--  Estudiante: William Duban Arrieta Caldera
--  Universidad Nacional Abierta y a Distancia UNAD
--  Mayo - 2026
--  Compatible con Oracle Database y Oracle APEX
-- ==============================================

-- =====================================================
-- 1. TABLA CLIENTE
-- =====================================================
CREATE TABLE CLIENTE (
    CLIENTE_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE            VARCHAR2(100) NOT NULL,
    IDENTIFICACION    VARCHAR2(20) UNIQUE NOT NULL,
    BARRIO            VARCHAR2(100),
    TELEFONO          VARCHAR2(20),
    CORREO            VARCHAR2(100),
    ESTADO            VARCHAR2(15) DEFAULT 'AL_DIA' CHECK (ESTADO IN ('AL_DIA', 'PENDIENTE')),
    PERIODOS_ACUMULADOS NUMBER DEFAULT 0,
    PLAN              VARCHAR2(50),
    MEGAS             NUMBER,
    PERIODO_CORTE     NUMBER CHECK (PERIODO_CORTE IN (5,10,15,20,25,30)),
    VALOR_FACTURA     NUMBER(12,2) NOT NULL,
    DIRECCION_IP      VARCHAR2(45),
    LATITUD           NUMBER(9,6),
    LONGITUD          NUMBER(9,6)
);

COMMENT ON TABLE CLIENTE IS 'Clientes prepago de la empresa de telecomunicaciones';
COMMENT ON COLUMN CLIENTE.ESTADO IS 'Estado del cliente: AL_DIA o PENDIENTE';


-- =====================================================
-- 2. TABLA FACTURA
-- =====================================================
CREATE TABLE FACTURA (
    FACTURA_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CLIENTE_ID        NUMBER NOT NULL,
    FECHA_GENERACION  DATE DEFAULT SYSDATE,
    PERIODO_CORTE     NUMBER CHECK (PERIODO_CORTE IN (5,10,15,20,25,30)),
    VALOR_FACTURA     NUMBER(12,2) NOT NULL,
    ESTADO            VARCHAR2(15) DEFAULT 'PENDIENTE' CHECK (ESTADO IN ('PAGADA', 'PENDIENTE')),
    NOTAS             CLOB,
    CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY (CLIENTE_ID)
        REFERENCES CLIENTE (CLIENTE_ID)
        ON DELETE CASCADE
);

COMMENT ON TABLE FACTURA IS 'Facturas generadas para clientes prepago';


-- =====================================================
-- 3. TABLA PAGO
-- =====================================================
CREATE TABLE PAGO (
    PAGO_ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CLIENTE_ID        NUMBER NOT NULL,
    FACTURA_ID        NUMBER NOT NULL,
    FECHA_PAGO        DATE DEFAULT SYSDATE,
    VALOR_PAGO        NUMBER(12,2) NOT NULL,
    MEDIO_PAGO        VARCHAR2(50),
    PAGO_PARCIAL      CHAR(1) DEFAULT 'N' CHECK (PAGO_PARCIAL IN ('S', 'N')),
    SALDO_PENDIENTE   NUMBER(12,2),
    CONSTRAINT FK_PAGO_CLIENTE FOREIGN KEY (CLIENTE_ID)
        REFERENCES CLIENTE (CLIENTE_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_PAGO_FACTURA FOREIGN KEY (FACTURA_ID)
        REFERENCES FACTURA (FACTURA_ID)
        ON DELETE CASCADE
);

COMMENT ON TABLE PAGO IS 'Pagos realizados por clientes (totales o parciales)';


-- =====================================================
-- 4. TABLA CUENTA_PUC
-- =====================================================
CREATE TABLE CUENTA_PUC (
    CUENTA_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODIGO_PUC        VARCHAR2(20) UNIQUE NOT NULL,
    NOMBRE_CUENTA     VARCHAR2(100) NOT NULL,
    NATURALEZA        VARCHAR2(10) CHECK (NATURALEZA IN ('DEBITO', 'CREDITO')),
    NIVEL             VARCHAR2(20) CHECK (NIVEL IN ('MAYOR', 'AUXILIAR', 'SUBCUENTA'))
);

COMMENT ON TABLE CUENTA_PUC IS 'Plan Único de Cuentas (PUC) para control contable';


-- =====================================================
-- 5. TABLA TRANSACCION
-- =====================================================
CREATE TABLE TRANSACCION (
    TRANSACCION_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FECHA             DATE DEFAULT SYSDATE,
    DESCRIPCION       VARCHAR2(200),
    TIPO              VARCHAR2(20) CHECK (TIPO IN ('INGRESO', 'EGRESO', 'AJUSTE'))
);

COMMENT ON TABLE TRANSACCION IS 'Transacciones contables registradas según PUC';


-- =====================================================
-- 6. TABLA MOVIMIENTO
-- =====================================================
CREATE TABLE MOVIMIENTO (
    MOVIMIENTO_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TRANSACCION_ID    NUMBER NOT NULL,
    CUENTA_ID         NUMBER NOT NULL,
    VALOR_DEBITO      NUMBER(12,2) DEFAULT 0,
    VALOR_CREDITO     NUMBER(12,2) DEFAULT 0,
    CONSTRAINT FK_MOV_TRANS FOREIGN KEY (TRANSACCION_ID)
        REFERENCES TRANSACCION (TRANSACCION_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_MOV_CUENTA FOREIGN KEY (CUENTA_ID)
        REFERENCES CUENTA_PUC (CUENTA_ID)
        ON DELETE CASCADE
);

COMMENT ON TABLE MOVIMIENTO IS 'Movimientos contables asociados a cada transacción';


-- =====================================================
-- 7. TABLA INFRAESTRUCTURA
-- =====================================================
CREATE TABLE INFRAESTRUCTURA (
    INFRAESTRUCTURA_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TIPO               VARCHAR2(50) NOT NULL,
    NOMBRE             VARCHAR2(100) NOT NULL,
    UBICACION          VARCHAR2(200),
    VALOR_ADQUISICION  NUMBER(12,2),
    FECHA_ADQUISICION  DATE,
    VIDA_UTIL          NUMBER,
    LATITUD            NUMBER(9,6),
    LONGITUD           NUMBER(9,6)
);

COMMENT ON TABLE INFRAESTRUCTURA IS 'Infraestructura técnica y física de la empresa';

